import { jsPDF } from "jspdf";
import type { FractureAnalysis } from "./analyze.functions";

function wrap(doc: jsPDF, text: string, width: number) {
  return doc.splitTextToSize(text, width) as string[];
}

export function downloadReport(analysis: FractureAnalysis, imageDataUrl: string | null) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = 0;

  // Header band
  doc.setFillColor(10, 46, 60);
  doc.rect(0, 0, pageW, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("FractureAI — Bone Fracture Analysis Report", margin, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated ${new Date().toLocaleString()}  ·  AI screening aid — not a medical diagnosis`,
    margin,
    21,
  );
  y = 40;

  // X-ray image
  if (imageDataUrl) {
    try {
      const imgW = 70;
      const imgH = 70;
      doc.setDrawColor(200, 210, 215);
      doc.rect(margin - 1, y - 1, imgW + 2, imgH + 2);
      doc.addImage(imageDataUrl, "JPEG", margin, y, imgW, imgH);
    } catch {
      // image embedding is best-effort
    }
  }

  // Diagnosis block (right of image)
  const dx = imageDataUrl ? margin + 78 : margin;
  const dw = pageW - dx - margin;
  doc.setTextColor(10, 46, 60);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Assessment", dx, y + 4);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);

  const verdict = analysis.fractureDetected ? "FRACTURE DETECTED" : "NO FRACTURE DETECTED";
  doc.setFont("helvetica", "bold");
  if (analysis.fractureDetected) {
    doc.setTextColor(180, 30, 30);
  } else {
    doc.setTextColor(20, 130, 70);
  }
  doc.text(verdict, dx, y + 12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);

  const meta = [
    `Confidence: ${Math.round(analysis.confidence * 100)}%`,
    `Region: ${analysis.boneRegion}`,
    `Fracture type: ${analysis.fractureType}`,
    `Severity: ${analysis.severity}`,
    `Urgency: ${analysis.urgency}`,
  ];
  let my = y + 19;
  for (const line of meta) {
    doc.text(line, dx, my);
    my += 6;
  }

  y = imageDataUrl ? y + 80 : my + 6;

  const section = (title: string, lines: string[]) => {
    if (y > 265) {
      doc.addPage();
      y = 20;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(10, 46, 60);
    doc.text(title, margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    for (const line of lines) {
      for (const wrapped of wrap(doc, line, contentW)) {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.text(wrapped, margin, y);
        y += 5.2;
      }
      y += 1.5;
    }
    y += 5;
  };

  section("Summary", [analysis.summary]);
  section(
    "Key Findings",
    analysis.findings.map((f) => `• ${f}`),
  );
  section(
    "Recommended Treatment Plan",
    analysis.treatmentPlan.map((t, i) => `${i + 1}. ${t}`),
  );

  // Footer disclaimer
  if (y > 262) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  for (const line of wrap(
    doc,
    "Disclaimer: This report is generated by an AI screening tool and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified physician or radiologist.",
    contentW,
  )) {
    doc.text(line, margin, y);
    y += 4;
  }

  doc.save(`fracture-analysis-report-${Date.now()}.pdf`);
}
